### ISSUE TITLE
chat.google.com forwards to mail.google.com, so no cookies found

### ISSUE THREAD

**Issue by erebion** [binfalse/matrix-gchat-bridge-login-cookie-generator#1]
Hello,

chat.google.com forwards to mail.google.com, so no cookies found:

"Could not find corresponding cookies"

Maybe instead check for the cookies on mail.google.com?

**Comment by erebion** [comment]
That is for the Firefox version.

(When trying to use the Chrome/Chromium version, the bridge just says "Those cookies don't seem to be valid".)

**Comment by binfalse** [comment]
Mmh, interesting. Taking the cookies for `mail.google.com` is not an option, because those seem to be different. Even though your browser redirects to that domain, the chat application still communicates with the endpoints at `chat.google.com` - and the bridge needs exactly those cookies...

Not sure what could be the issue in your case, though. You can use the chat in the browser but the addon still does not show the login cookie command?

I just uploaded a new version (`1.1.7`) to the Mozilla addon directory: https://addons.mozilla.org/en-US/firefox/addon/gchat-login-cookie-generator/

Could you please give that a try? It will tell you which cookie is missing - which will hopefully help to debug the issue.

**Comment by erebion** [comment]
@binfalse v1.1.7 works! No complaints here. :)

Thanks for making this!
